---
abstract: 'portably run blocking code and programs in subprocesses'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Wheel-Run-Win32
no_index:
  directory:
    - inc
    - t
provides:
  POE::Wheel::Run::Win32:
    file: lib/POE/Wheel/Run/Win32.pm
    version: 0.18
requires:
  POE: 1.28
  Win32: 0
  Win32::Job: 0
  Win32::Process: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-wheel-run-win32/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-wheel-run-win32.git
version: 0.18
